AtlasSite/AtlasSite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('MapDisplayer/', include('MapDisplayer.urls'), name='MapDisplayer'),
    path('MapEditor/', include('MapEditor.urls'), name='MapEditor'),
]

AtlasSite/MapDisplayer/urls.py
from django.urls import path

from . import views
app_name = 'MapDisplayer'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:mapID>/viewMap/', views.viewMap, name='displayMap'),
	path('getRegionFromCoordinates/', views.getRegionFromCoordinates, name='getRegion'),
	path('loadRegion/',views.loadRegion, name='loadRegion'),
	path('browseMaps/',views.browseMaps, name='browseMaps'),
	path('search/',views.search, name='search'),
]

AtlasSite/MapEditor/urls.py
from django.urls import path

from . import views
app_name = 'MapEditor'
urlpatterns = [
	path('', views.editIndex, name='editIndex'),
	path('<int:mapID>', views.editMap, name='editMap'),
]

AtlasSite/MapDisplayer/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
# Create your models here.


class Map(models.Model):
    parentMap = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    width = models.IntegerField()
    height = models.IntegerField()
    imageURL = models.CharField(max_length=100, default='')
    name = models.CharField(max_length=100, default='ni')
    summary = models.CharField(max_length=500, default='')
    full_link = models.CharField(max_length=100, default='')
    indices = ArrayField(models.IntegerField(default=0), default=list)
    isPrivate = models.BooleanField(default=False)
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, related_name='Owned_Maps')
    viewers = models.ManyToManyField(User, blank=True, related_name='Accesible_Maps')

    def __str__(self):
        return self.name


class Region(models.Model):
    summary_link = models.CharField(max_length=100)
    full_link = models.CharField(max_length=100)
    indices = ArrayField(models.IntegerField())
    map_im_in = models.ForeignKey(
        Map,
        on_delete=models.CASCADE,)
    name = models.CharField(max_length=100, default='ni')

    def __str__(self):
        return self.name

AtlasSite/MapEditor/models.py
from django.db import models

# Create your models here.

AtlasSite/MapEditor/forms.py
from django import forms

from MapDisplayer.models import Map

class MapForm(forms.Form):
	name = forms.CharField(label='Map Name', max_length=100)
	summary = forms.CharField(label='Map Summary', max_length=1000)
	full_link = forms.CharField(label='External Link', max_length=100)
	is_private = forms.BooleanField(label='Is Map Private?')
	
	

AtlasSite/MapDisplayer/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
# Create your views here.
from .models import  Map
from django.template import loader
import math
from django.db.models import Q
from django.utils.html import escape
from django.core import serializers

def index(request):
	PublicMaps = Map.objects.all().filter(isPrivate=False)
	MapsICanView = request.user.Accesible_Maps.all()
	MapsIOwn = request.user.Owned_Maps.all() 
	#Maps = PublicMaps | MapsICanView | MapsIOwn
	Maps = MapsICanView
	print(MapsICanView)
	print(MapsIOwn)
	context = {
		'Accessible_Maps': MapsICanView,
		'My_Maps': MapsIOwn,
	}
	return render(request, 'MapDisplayer/index.html',context)

def browseMaps(request):
	current_user = request.user
	print (current_user.id)
	return render(request, 'MapDisplayer/browse.html')

def viewMap(request, mapID):
	mapToView = get_object_or_404(Map,pk=mapID)
	return render(request, 'MapDisplayer/viewMap.html',{'mapToView':mapToView })

def getRegionFromCoordinates(request):
	x= request.GET.get('x',0)
	y= request.GET.get('y',0)
	mapID = request.GET.get('mapID',0)
	mapInQuestion = get_object_or_404(Map,pk=mapID)
	width=mapInQuestion.width
	height=mapInQuestion.height
	x=float(x)
	y=float(y)
			
	XCoord = x*width
	YCoord = y*height

	XCoord = math.floor(XCoord)
	YCoord = math.floor(YCoord)
	
	summaryURL = ""
	name=""
	regionIndex= XCoord+YCoord*width
	regions = mapInQuestion.map_set.all()
	summary = ""
	regionID= -1
	url=""
	#regionToReturn=None;
	for region in regions:
		indices = region.indices
		for index in indices:
			if index==regionIndex: 
				summaryURL = region.full_link
				name=region.name
				summary=region.summary
				regionID=region.id
				url=region.imageURL
				
	data= {
		'X': x,
		'Y': y,
		'Index':regionIndex,
		'URL': url,
		'Summary':summary,
		'ID':regionID,
		'full_link_URL':summaryURL,
		'map_name':name,
		}
	return JsonResponse(data)

def loadRegion(request):
	mapID = request.GET.get('mapID',-1)
	mapToLoad = get_object_or_404(Map,pk=mapID)
	data= {
		'imageURL' : mapToLoad.imageURL,
		'name' : mapToLoad.name,
		'summary' : mapToLoad.summary,
		'full_link' : mapToLoad.full_link,
		}
	return JsonResponse(data)
def search(request):
	q = request.GET.get('key','')
	print(q)
	query_list=q.split()
	Maps=Map.objects.none()
	for query in query_list:
	   Maps = Maps | Map.objects.all().filter(isPrivate=False, name__icontains=query)
	 
	print(Maps)
	mapData =[]
	for aMap in Maps:
		mapData.append({
				'id':aMap.id,
				'name':aMap.name,
			     })	
	#mapData= serializers.serialize('json', Maps, fields=('name','id'))
	data = {
		'data':mapData,
		}
	return JsonResponse(data)

AtlasSite/MapEditor/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse

from .forms import MapForm
from MapDisplayer.models import Map
from django.template import loader
# Create your views here.
def editMap(request,mapID):
	mapToEdit = get_object_or_404(Map,pk=mapID)
	if(request.method=='POST'):
		print("You did a post!")
		print(request.POST.get('name'))
		form = MapForm(request.POST)
		print(form['name'].value())
		form.is_valid()
		#print(request.POST.get('viewers[]')[0])
		#print(form.cleaned_data['name'])
		#print( request.POST['name'])
		mapToEdit.name=request.POST.get('name')
		mapToEdit.save()
	else:
		form = MapForm()
	
	return render(request, 'MapEditor/mapBuilder.html',{'mapToView':mapToEdit,'Form':form})

def editIndex(request):
	MapsICanEdit = request.user.Owned_Maps.all()
	context = {
		'MapsICanEdit':MapsICanEdit,
		}
	return render(request, 'MapEditor/index.html', context)

AtlasSite/AtlasSite/templates/base.html
<html>
	<head>
	</head>
	<body>
		{% block nav %}
		<ul id="nav">
			<li>{% block nav-home %}<a href="{% url 'MapDisplayer:index' %}">Home</a>{% endblock %}</li>
			<li>{% block nav-browse %}<a href="{% url 'MapDisplayer:browseMaps' %}">Browse</a>{% endblock %}</li>
			<li>{% block nav-create %}<a href="">Create</a>{% endblock %}</li>
			<li>{% block nav-edit %}<a href="{% url 'MapEditor:editIndex' %}">Edit</a>{% endblock %}</li>
		</ul>
		{% endblock %}
		{% block Content %}
		{% endblock %}
	</body>
</html>

AtlasSite/MapDisplayer/templates/MapDisplayer/browse.html
{% extends 'base.html' %}
{% load static %}
{% block Content %}
<form id="search-form">
	<input type="text" id="search-bar"/>
	<input type="button"  id="search-button"/>
</form>
<div id="map-list">
</div>
<script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
<script src="{% static 'MapDisplayer/Search.js' %}"></script>
{% endblock %}

AtlasSite/MapDisplayer/templates/MapDisplayer/index.html
{% extends "base.html" %}
{% block Content %}
<p>My Maps</p>
{% if My_Maps %}
	<ul>
	{% for map in My_Maps %}
		<li><a href="/MapDisplayer/{{map.id}}/viewMap/">{{map.name}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>You own no maps!</p>
{% endif %}
<br>
<p>Maps I have access to!!!</p>
<p>Just adding something random for a test</p>
{% if Accessible_Maps %}
	<ul>
	{%for map in Accessible_Maps %}
		<li><a href="/MapDisplayer/{{map.id}}/viewMap/">{{map.name}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>You have no maps you can visit!</p>
{% endif %}
{% endblock %}

AtlasSite/MapDisplayer/templates/MapDisplayer/viewMap.html
{% extends 'base.html' %}
{% block Content %}
{{mapToView}}
{% load static %}
{% with "MapDisplayer/"|add:mapToView.imageURL as URL %}
<html>
    <head>
	<meta charset="utf-8">
	<title>
	    Check out some cool maps
	</title>
	{% load js %}
	<script> 
		var currentMapID = {{ mapToView.id | js }};
		var currentMap;
		var mapSelected = false;
		var mapSelectedID;
		var map = {
				'summary': {{mapToView.summary | js}},
				'full_link': {{mapToView.full_link | js}},
				'imageURL': {{mapToView.imageURL | js}},
				'name': {{mapToView.name | js}},
				'ID': {{mapToView.id | js}},
			}
		var mapList = []
		var navIndex=0;
		mapList[navIndex]= map;
		
	</script>
	<script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
	<script src="{% static 'MapDisplayer/GetCoordinates.js' %}"></script>	
    </head>
    <body>
	<button id="back">Back</button>
	<button id="next">Next</button>
	<div>
            <div style="float:left;">
	        <img src="{% static URL %}"  alt="Map" style="height:600px;width:700px" id="test"/>
            </div>
	    <div style="float:right;">
		<h1 id="mapName">{{ mapToView.name }}</h1>
	    	<p id="mapSummary">
			{{ mapToView.summary }}
		</p>
		<a href="" id="detailLink" target="_blank" >Full Details Here</a>
	    </div>
	<div>
		<button id="Load">Load</button>
	</div>
    </body>
</html>
{% endwith %} 
{% endblock %}

AtlasSite/MapDisplayer/templates/MapDisplayer/viewMapBase.html
{{mapToView}}
{% load static %}
{% with "MapDisplayer/"|add:mapToView.imageURL as URL %}
	
	<div>
	{% block Map %}
            <div style="float:left;">
	        <img src="{% static URL %}"  alt="Map" style="height:600px;width:700px" id="test"/>
            </div>
	{% endblock %}
	{% block Info %}
	    <div style="float:right;">
		<h1 id="mapName">{{ mapToView.name }}</h1>
	    	<p id="mapSummary">
			{{ mapToView.summary }}
		</p>
		<a href="" id="detailLink" target="_blank" >Full Details Here</a>
	    </div>
	{% endblock %}
{% endwith %} 

AtlasSite/MapDisplayer/templates/viewMapBase.html
{{mapToView}}
{% load static %}
{% with "MapDisplayer/"|add:mapToView.imageURL as URL %}

	{% block Map %}
            <div style="float:left;">
	        <img src="{% static URL %}"  alt="Map" style="height:600px;width:700px" id="test"/>
            </div>
	{% endblock %}
	{% block Info %}
	    <div style="float:right;">
		<h1 id="mapName">{{ mapToView.name }}</h1>
	    	<p id="mapSummary">
			{{ mapToView.summary }}
		</p>
		<a href="" id="detailLink" target="_blank" >Full Details Here</a>
	    </div>
	{% endblock %}
{% endwith %} 

AtlasSite/MapEditor/templates/MapEditor/index.html
{% extends 'base.html' %}
{% block Content %}
<p>Maps I can edit</p>
{% if MapsICanEdit %}
	<ul>
	{%for map in MapsICanEdit %}
		<li><a href="/MapEditor/{{map.id}}">{{map.name}}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>You have no maps to edit, try creating a new map</p>
{% endif %}
{% endblock %}

AtlasSite/MapEditor/templates/MapEditor/mapBuilder.html
{% extends 'viewMapBase.html' %}
{% block Info %}
<form action="" method="POST">
	{% csrf_token %}	
	<input type = "text" value="{{mapToView.name}}" id="map-name" name="name">Map Name</input>
	<br>
	<textarea name= "summary" value="{{mapToView.summary}}" id="map-summary">{{mapToView.summary}}</textarea>
	<br>
	<input type = "text" name="full_link" value="{{mapToView.full_link}}" id=map-link">External Link</input>
	<br>
	<input type = "checkbox" name="isPrivate" value={{mapToView.isPrivate}}" id="map-isPrivate">Is Map Private?</input>
	<br>
	<input type="submit" id="submit-map"></input>
	 
</form>
{% endblock %}